/**
 * Regenerates golden XDR fixtures under src/stellar/xdr-fixtures/.
 *
 * Run after an intentional ABI / encoder change:
 *   npx ts-node scripts/regenerate-xdr-fixtures.ts
 *
 * Do NOT regenerate to silence a failing test without first confirming whether
 * the contract ABI changed or the encoding regressed.
 */
import * as fs from "fs";
import * as path from "path";
import { Address, Keypair, nativeToScVal, xdr } from "@stellar/stellar-sdk";
import {
  COVERAGE_TYPE_VARIANTS,
  TRIGGER_THRESHOLDS,
  buildPolicyParamsScVal,
  encodeOraclePublishArgs,
  encodeProcessClaimArg,
  encodeProvideCapitalArgs,
  encodeWithdrawCapitalArgs,
} from "../src/stellar/scval-encoders";

const outDir = path.join(__dirname, "../src/stellar/xdr-fixtures");

const header =
  "// Golden XDR fixtures for hand-built ScVal encodings.\n" +
  "// Regenerated by: npx ts-node scripts/regenerate-xdr-fixtures.ts\n" +
  "// A mismatch means either the contract ABI changed or the encoding regressed —\n" +
  "// check both before regenerating.\n";

function writeB64(name: string, scVal: xdr.ScVal, note?: string): void {
  const body = header + (note ? `// ${note}\n` : "") + scVal.toXDR("base64") + "\n";
  fs.writeFileSync(path.join(outDir, name), body);
}

fs.mkdirSync(outDir, { recursive: true });

const amounts = [
  10_000n * 10_000_000n,
  25_000n * 10_000_000n,
  50_000n * 10_000_000n,
  2n ** 60n,
  1_000n * 10_000_000n,
];
const days = [30, 90, 180, 365, 7];

for (let i = 0; i < COVERAGE_TYPE_VARIANTS.length; i++) {
  const sc = buildPolicyParamsScVal({
    coverageType: i,
    coverageAmount: amounts[i],
    durationDays: days[i],
    triggerThreshold: TRIGGER_THRESHOLDS[i],
  });
  writeB64(
    `policy-params-${COVERAGE_TYPE_VARIANTS[i]}.xdr.b64`,
    sc,
    `coverageType=${i} amount=${amounts[i]} days=${days[i]} threshold=${TRIGGER_THRESHOLDS[i]}`
  );
}

writeB64(
  "policy-params-large-i128.xdr.b64",
  buildPolicyParamsScVal({
    coverageType: 0,
    coverageAmount: 2n ** 60n,
    durationDays: 30,
    triggerThreshold: 500,
  }),
  "amount=2^60"
);

writeB64("process-claim-u64.xdr.b64", encodeProcessClaimArg(42n));

const seed = Buffer.alloc(32, 7);
const kp = Keypair.fromRawEd25519Seed(seed);
const [providerSc, amountSc] = encodeProvideCapitalArgs(kp.publicKey(), 10_000_000_000n);
const [, sharesSc] = encodeWithdrawCapitalArgs(kp.publicKey(), 5_000_000_000n);
writeB64("provide-capital-provider.xdr.b64", providerSc);
writeB64("provide-capital-amount.xdr.b64", amountSc);
writeB64("withdraw-capital-shares.xdr.b64", sharesSc);
fs.writeFileSync(
  path.join(outDir, "provide-capital-meta.json"),
  JSON.stringify({ providerPubkey: kp.publicKey(), amount: "10000000000", shares: "5000000000" }, null, 2) + "\n"
);

const [feed, value, ts] = encodeOraclePublishArgs("USDC_USD", 9_500_000n, 1_700_000_000n);
writeB64("oracle-publish-feed.xdr.b64", feed);
writeB64("oracle-publish-value.xdr.b64", value);
writeB64("oracle-publish-timestamp.xdr.b64", ts);

// silence unused import if tree-shaken oddly
void Address;
void nativeToScVal;

console.log(`Regenerated fixtures in ${outDir}`);
